apiVersion: batch/v1
kind: Job
metadata:
  name: jenkinsdemo
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: jenkinsdemo
          image: us-east1-docker.pkg.dev/project-dcd1a2c8-b069-4b5b-8d4/jenkinsdemo/my-dotnet-app:latest
  backoffLimit: 1